/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileType } from './file-type';
import { User } from './user';
/**
 * 
 * @export
 * @interface Agency
 */
export interface Agency {
    /**
     * 
     * @type {User}
     * @memberof Agency
     */
    owner: User;
    /**
     * 
     * @type {FileType}
     * @memberof Agency
     */
    logo: FileType | null;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    address: string | null;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    website: string | null;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Agency
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof Agency
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Agency
     */
    updatedAt: Date;
}
