/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthRegisterLoginDto
 */
export interface AuthRegisterLoginDto {
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterLoginDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterLoginDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterLoginDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterLoginDto
     */
    lastName: string;
}
