/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthResetPasswordDto
 */
export interface AuthResetPasswordDto {
    /**
     * 
     * @type {string}
     * @memberof AuthResetPasswordDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthResetPasswordDto
     */
    hash: string;
}
