/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthAppleLoginDto
 */
export interface AuthAppleLoginDto {
    /**
     * 
     * @type {string}
     * @memberof AuthAppleLoginDto
     */
    idToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAppleLoginDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAppleLoginDto
     */
    lastName?: string;
}
