/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileDto } from './file-dto';
/**
 * 
 * @export
 * @interface AuthUpdateDto
 */
export interface AuthUpdateDto {
    /**
     * 
     * @type {FileDto}
     * @memberof AuthUpdateDto
     */
    photo?: FileDto;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUpdateDto
     */
    oldPassword?: string;
}
