/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TourDto } from './tour-dto';
/**
 * 
 * @export
 * @interface CreatePackageDto
 */
export interface CreatePackageDto {
    /**
     * 
     * @type {TourDto}
     * @memberof CreatePackageDto
     */
    tour: TourDto;
    /**
     * 
     * @type {number}
     * @memberof CreatePackageDto
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePackageDto
     */
    minParticipant?: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePackageDto
     */
    maxParticipant?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePackageDto
     */
    name: string;
}
