/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TourCategory } from './tour-category';
/**
 * 
 * @export
 * @interface InfinityPaginationTourCategoryResponseDto
 */
export interface InfinityPaginationTourCategoryResponseDto {
    /**
     * 
     * @type {Array<TourCategory>}
     * @memberof InfinityPaginationTourCategoryResponseDto
     */
    data: Array<TourCategory>;
    /**
     * 
     * @type {boolean}
     * @memberof InfinityPaginationTourCategoryResponseDto
     */
    hasNextPage: boolean;
}
