/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Agency } from './agency';
/**
 * 
 * @export
 * @interface InfinityPaginationAgencyResponseDto
 */
export interface InfinityPaginationAgencyResponseDto {
    /**
     * 
     * @type {Array<Agency>}
     * @memberof InfinityPaginationAgencyResponseDto
     */
    data: Array<Agency>;
    /**
     * 
     * @type {boolean}
     * @memberof InfinityPaginationAgencyResponseDto
     */
    hasNextPage: boolean;
}
