/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * 
 * @export
 * @interface InfinityPaginationUserResponseDto
 */
export interface InfinityPaginationUserResponseDto {
    /**
     * 
     * @type {Array<User>}
     * @memberof InfinityPaginationUserResponseDto
     */
    data: Array<User>;
    /**
     * 
     * @type {boolean}
     * @memberof InfinityPaginationUserResponseDto
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {number}
     * @memberof InfinityPaginationUserResponseDto
     */
    totalCount: number;
}
