/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tour } from './tour';
/**
 * 
 * @export
 * @interface InfinityPaginationTourResponseDto
 */
export interface InfinityPaginationTourResponseDto {
    /**
     * 
     * @type {Array<Tour>}
     * @memberof InfinityPaginationTourResponseDto
     */
    data: Array<Tour>;
    /**
     * 
     * @type {boolean}
     * @memberof InfinityPaginationTourResponseDto
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {number}
     * @memberof InfinityPaginationTourResponseDto
     */
    totalCount: number;
}
