/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * 
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDto
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDto
     */
    refreshToken: string;
    /**
     * 
     * @type {number}
     * @memberof LoginResponseDto
     */
    tokenExpires: number;
    /**
     * 
     * @type {User}
     * @memberof LoginResponseDto
     */
    user: User;
}
