/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tour } from './tour';
/**
 * 
 * @export
 * @interface ModelPackage
 */
export interface ModelPackage {
    /**
     * 
     * @type {Tour}
     * @memberof ModelPackage
     */
    tour: Tour;
    /**
     * 
     * @type {number}
     * @memberof ModelPackage
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof ModelPackage
     */
    minParticipant: number | null;
    /**
     * 
     * @type {number}
     * @memberof ModelPackage
     */
    maxParticipant: number | null;
    /**
     * 
     * @type {string}
     * @memberof ModelPackage
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPackage
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ModelPackage
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ModelPackage
     */
    updatedAt: Date;
}
