/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TourCategory } from './tour-category';
/**
 * 
 * @export
 * @interface TourCategory
 */
export interface TourCategory {
    /**
     * 
     * @type {TourCategory}
     * @memberof TourCategory
     */
    parent: TourCategory | null;
    /**
     * 
     * @type {Array<TourCategory>}
     * @memberof TourCategory
     */
    childCategories: Array<TourCategory> | null;
    /**
     * 
     * @type {string}
     * @memberof TourCategory
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourCategory
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TourCategory
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TourCategory
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TourCategory
     */
    updatedAt: Date;
}
