/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TourCategoryDto } from './tour-category-dto';
/**
 * 
 * @export
 * @interface UpdateTourDto
 */
export interface UpdateTourDto {
    /**
     * 
     * @type {Array<any>}
     * @memberof UpdateTourDto
     */
    itinerary?: Array<any> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTourDto
     */
    onSale?: boolean;
    /**
     * 
     * @type {TourCategoryDto}
     * @memberof UpdateTourDto
     */
    category?: TourCategoryDto;
    /**
     * 
     * @type {string}
     * @memberof UpdateTourDto
     */
    additionalInfo?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateTourDto
     */
    exclusions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateTourDto
     */
    inclusions?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTourDto
     */
    isAvailable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateTourDto
     */
    highlights?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTourDto
     */
    duration?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateTourDto
     */
    discountPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateTourDto
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTourDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTourDto
     */
    title?: string;
}
