/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileDto } from './file-dto';
import { RoleDto } from './role-dto';
import { StatusDto } from './status-dto';
/**
 * 
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    lastName?: string;
    /**
     * 
     * @type {FileDto}
     * @memberof UpdateUserDto
     */
    photo?: FileDto;
    /**
     * 
     * @type {RoleDto}
     * @memberof UpdateUserDto
     */
    role?: RoleDto;
    /**
     * 
     * @type {StatusDto}
     * @memberof UpdateUserDto
     */
    status?: StatusDto;
}
