/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileDto } from './file-dto';
/**
 * 
 * @export
 * @interface UpdateAgencyDto
 */
export interface UpdateAgencyDto {
    /**
     * 
     * @type {FileDto}
     * @memberof UpdateAgencyDto
     */
    logo?: FileDto;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgencyDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgencyDto
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgencyDto
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgencyDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAgencyDto
     */
    name?: string;
}
