/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/agencies-api';
export * from './apis/auth-api';
export * from './apis/files-api';
export * from './apis/home-api';
export * from './apis/packages-api';
export * from './apis/tourcategories-api';
export * from './apis/tours-api';
export * from './apis/users-api';

